In [ ]:
pip install pandas openpyxl

In [ ]:
import pandas as pd
df=pd.read_excel('Brand_Protection_Realistic_Raw_Data.xlsx')
df.head()

,S.no,Month sequence,Year,Quarter,Month,Third party brand,Platform Type,Platform Group,Platform,Platform domain,...,Number of transactions/number of requests of quotation,Minimum order quantities,Type of product,Type of Ip Right Violated,Status,Infringement Type,Remarks,Date of analysis,Currency,Price
0,1,4,2025,Q2,April,NaN,E-commerce,Marketplace,Alibaba,alibaba.com,...,5,5,Razor Cartridge,Labs Cartridge Pattern,Inactive,Counterfeit,NaN,25/04/2025,NaN,$212.29
1,2,3,2026,Q1,March,NaN,E-commerce,Marketplace,Shopee,shopee.com.my,...,RFQ only,10,Razor Handle,M3 Handle Design,Inactive,Counterfeit,NaN,06-Mar-26,NaN,Aktueller Preis Ab 6 €
2,3,1,2026,Q1,January,NaN,E-commerce,Marketplace,Deal,deal.by,...,100+,1,Razor,3D Alpha Mark (Blue),Inactive,counterfeit,NaN,03-Jan-26,NaN,Rp82.800 - Rp99.000
3,4,8,2025,Q3,August,UltraTrim,E-commerce,Marketplace,Amazon,amazon.de,...,100+,1 Piece,Razor Handle,M3 Handle Design,Inactive,Counterfeit,NaN,27/08/2025,NaN,17 €
4,5,9,2025,Q3,September,NaN,E-commerce,Marketplace,1688,1688.com,...,0,10,Trimmer,Omega Trimmer Shape,Inactive,Counter Fit,NaN,2025-09-08,NaN,$212.29

In [4]:
df.shape

(29995, 25)

In [3]:
df.columns.tolist()

['S.no',
 'Month sequence',
 'Year',
 'Quarter',
 'Month',
 'Third party brand',
 'Platform Type',
 'Platform Group',
 'Platform',
 'Platform domain',
 'Country',
 'Region',
 'Seller Name',
 'URL',
 'Item No.',
 'Store URL',
 'Number of items available',
 'Number of transactions/number of requests of quotation',
 'Minimum order quantities',
 'Type of product',
 'Type of Ip Right Violated',
 'Status',
 'Infringement Type',
 'Remarks',
 'Date of analysis',
 'Currency',
 'Price']

In [5]:
df.isnull().sum()

S.no                                                      0
Month sequence                                            0
Year                                                      0
Quarter                                                   0
Month                                                     0
Third party brand                                         0
Platform Type                                             0
Platform                                                  0
Platform domain                                           0
Country                                                   0
Region                                                    0
Seller Name                                               0
URL                                                       0
Item No.                                                  0
Store URL                                                 0
Number of items available                                 0
Number of transactions/number of requests of quotation    0
Minimum order quantities                                  0
Type of product                                           0
Type of Ip Right Violated                                 0
Status                                                    0
Infringement Type                                         0
Date of analysis                                          0
Currency                                                  0
Price                                                     0
dtype: int64

In [6]:
#check for duplicated rows
df.duplicated().sum()

np.int64(0)

In [6]:
#Remove duplicated rows.
df = df.drop_duplicates()

In [7]:
df['URL'].duplicated().sum()

np.int64(0)

In [3]:
df[df['URL'].duplicated(keep=False)].sort_values('URL')

,S.no,Month sequence,Year,Quarter,Month,Third party brand,Platform Type,Platform,Platform domain,Country,...,Number of items available,Number of transactions/number of requests of quotation,Minimum order quantities,Type of product,Type of Ip Right Violated,Status,Infringement Type,Date of analysis,Currency,Price
13719,13720,9,2025,3,September,-,E-commerce,1688,1688.com,India,...,1.0,25,50,Razor Cartridge,Labs Cartridge Pattern,Removed,Trademark,2025-09-25,GBP,15.99
1160,1161,1,2025,1,January,-,E-commerce,1688,1688.com,China,...,119.0,0,1,Razor Handle,Flexball Handle Design,Removed,Design,2025-01-29,IDR,90.00
13645,13646,8,2025,3,August,FlexEdge,E-commerce,1688,1688.com,Indonesia,...,194.0,23000,500,Razor Cartridge,Labs Cartridge Pattern,Removed,Trademark,2025-08-09,IDR,90.00
12638,12639,8,2025,3,August,-,E-commerce,1688,1688.com,Indonesia,...,1.0,25,500,Razor Cartridge,Labs Cartridge Pattern,Removed,Trademark,2025-08-09,IDR,90.00
21732,21733,1,2026,1,January,TurboEdge,E-commerce,1688,1688.com,India,...,402.0,100,10,Razor Cartridge,Fusion Shade Mark,Removed,Trademark,2026-01-01,SEK,129.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6317,6318,4,2025,2,April,-,Social Media,Tiktok,Tiktok.com,Malaysia,...,427.0,0,500,Razor Handle,Vector Shape Mark,Removed,Trademark,2025-04-23,MYR,28.90
22149,22150,1,2026,1,January,-,Social Media,Tiktok,Tiktok.com,China,...,438.0,10,50,Razor Cartridge,Fusion Shade Mark,Active,Trademark,2026-01-23,EUR,11.99
22158,22159,1,2026,1,January,-,Social Media,Tiktok,Tiktok.com,China,...,10.0,10,50,Razor Cartridge,Fusion Shade Mark,Removed,Trademark,2026-01-23,EUR,11.99
11987,11988,8,2025,3,August,-,Social Media,Tiktok,Tiktok.com,India,...,10.0,25,10,Razor Handle,Vector Shape Mark,Removed,Trademark,2025-08-04,EUR,17.00
13634,13635,8,2025,3,August,-,Social Media,Tiktok,Tiktok.com,India,...,133.0,25,10,Razor Handle,Vector Shape Mark,Removed,Trademark,2025-08-04,EUR,17.00

In [4]:
df = df.drop_duplicates(subset='URL', keep='first')

In [7]:
df.describe(include='all')

,S.no,Month sequence,Year,Quarter,Month,Third party brand,Platform Type,Platform Group,Platform,Platform domain,...,Number of transactions/number of requests of quotation,Minimum order quantities,Type of product,Type of Ip Right Violated,Status,Infringement Type,Remarks,Date of analysis,Currency,Price
count,30260.000000,30260.000000,30260.000000,30260,30260,4485,30260,30260,30260,30260,...,30260.0,30260.0,30260,30260,30260,30260,0.0,30260,0.0,30260
unique,NaN,NaN,NaN,4,12,341,2,1,24,27,...,45.0,6.0,5,9,7,4,NaN,1623,NaN,20
top,NaN,NaN,NaN,Q1,January,SharpEdge,E-commerce,Marketplace,Tiktok,Tiktok.com,...,0.0,50.0,Razor Handle,Flexball Handle Design,Removed,Counter Fit,NaN,2025-07-11,NaN,$212.29
freq,NaN,NaN,NaN,10065,3485,357,28911,30260,1349,1349,...,4398.0,5149.0,10293,3446,28982,7694,NaN,34,NaN,1593
mean,15006.453106,5.517019,2025.324289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,8660.629911,3.325815,0.468117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,1.000000,2025.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,7512.750000,3.000000,2025.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,15005.500000,5.000000,2025.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,22507.250000,8.000000,2026.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,30000.000000,12.000000,2026.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#Remove Q from quater and change data type to numerical
df['Quarter']=df['Quarter'].str.replace('Q','',regex=False).astype(int)

In [9]:
#Check unique quarters
df['Quarter'].unique()

array([2, 1, 3, 4])

In [10]:
df.head()

,S.no,Month sequence,Year,Quarter,Month,Third party brand,Platform Type,Platform Group,Platform,Platform domain,...,Number of transactions/number of requests of quotation,Minimum order quantities,Type of product,Type of Ip Right Violated,Status,Infringement Type,Remarks,Date of analysis,Currency,Price
0,1,4,2025,2,April,NaN,E-commerce,Marketplace,Alibaba,alibaba.com,...,5,5,Razor Cartridge,Labs Cartridge Pattern,Inactive,Counterfeit,NaN,25/04/2025,NaN,$212.29
1,2,3,2026,1,March,NaN,E-commerce,Marketplace,Shopee,shopee.com.my,...,RFQ only,10,Razor Handle,M3 Handle Design,Inactive,Counterfeit,NaN,06-Mar-26,NaN,Aktueller Preis Ab 6 €
2,3,1,2026,1,January,NaN,E-commerce,Marketplace,Deal,deal.by,...,100+,1,Razor,3D Alpha Mark (Blue),Inactive,counterfeit,NaN,03-Jan-26,NaN,Rp82.800 - Rp99.000
3,4,8,2025,3,August,UltraTrim,E-commerce,Marketplace,Amazon,amazon.de,...,100+,1 Piece,Razor Handle,M3 Handle Design,Inactive,Counterfeit,NaN,27/08/2025,NaN,17 €
4,5,9,2025,3,September,NaN,E-commerce,Marketplace,1688,1688.com,...,0,10,Trimmer,Omega Trimmer Shape,Inactive,Counter Fit,NaN,2025-09-08,NaN,$212.29

In [11]:
df['Platform Type'].unique()

array(['E-commerce', 'Social Media'], dtype=object)

In [12]:
#df['Platform'].value_counts()
#df['Country'].value_counts()
#df['Third party brand'].value_counts(dropna=False)
df['Infringement Type'].value_counts()

Infringement Type
Counter Fit         7694
Counterfeit         7583
Trademark Misuse    7500
counterfeit         7483
Name: count, dtype: int64

In [13]:
df.head()

,S.no,Month sequence,Year,Quarter,Month,Third party brand,Platform Type,Platform Group,Platform,Platform domain,...,Number of transactions/number of requests of quotation,Minimum order quantities,Type of product,Type of Ip Right Violated,Status,Infringement Type,Remarks,Date of analysis,Currency,Price
0,1,4,2025,2,April,NaN,E-commerce,Marketplace,Alibaba,alibaba.com,...,5,5,Razor Cartridge,Labs Cartridge Pattern,Inactive,Counterfeit,NaN,25/04/2025,NaN,$212.29
1,2,3,2026,1,March,NaN,E-commerce,Marketplace,Shopee,shopee.com.my,...,RFQ only,10,Razor Handle,M3 Handle Design,Inactive,Counterfeit,NaN,06-Mar-26,NaN,Aktueller Preis Ab 6 €
2,3,1,2026,1,January,NaN,E-commerce,Marketplace,Deal,deal.by,...,100+,1,Razor,3D Alpha Mark (Blue),Inactive,counterfeit,NaN,03-Jan-26,NaN,Rp82.800 - Rp99.000
3,4,8,2025,3,August,UltraTrim,E-commerce,Marketplace,Amazon,amazon.de,...,100+,1 Piece,Razor Handle,M3 Handle Design,Inactive,Counterfeit,NaN,27/08/2025,NaN,17 €
4,5,9,2025,3,September,NaN,E-commerce,Marketplace,1688,1688.com,...,0,10,Trimmer,Omega Trimmer Shape,Inactive,Counter Fit,NaN,2025-09-08,NaN,$212.29

In [14]:
df['Platform'].value_counts()

Platform
Tiktok          1349
Bol             1315
DHgate          1308
Amazon          1306
Shopee          1305
Fruugo          1289
Cdiscount       1282
Kaufland        1279
Joom            1276
JD              1269
Fyndiq          1265
Deal            1257
CDON            1257
MercadoLibre    1254
Daraz           1245
eMAG            1245
eBay            1245
AliExpress      1243
Allegro         1240
1688            1237
Lazada          1226
Desertcart      1219
Alibaba         1186
Bonanza         1163
Name: count, dtype: int64

In [ ]:
df.head()

For Number of items available

In [33]:
df['Number of items available'].sample(20)

18645                          249
9142                           325
18219                          354
261                           7769
21421                           98
6350                            86
16328                           72
29955                          211
3950                      IN STOCK
18386                     IN STOCK
14479     jumlah\n\nStok Total: 94
458                            477
18095                          106
360                       IN STOCK
28990                          141
30460                          392
27533    jumlah\n\nStok Total: 445
1552                            90
10268                          283
24322                           72
Name: Number of items available, dtype: object

In [34]:
df['Items_clean'] = df['Number of items available']

In [36]:
df['Items_clean'].isna().sum()

np.int64(0)

In [37]:
df['Items_clean'] = df['Items_clean'].astype(str)

In [42]:
df[['Number of items available','Items_clean']].sample(20)

      Number of items available            Items_clean
7225                        210                    210
16564     Mehr als 10 verfügbar  Mehr als 10 verfügbar
18865                         2                      2
15657                       280                    280
6086                         60                     60
5705                        368                    368
14209     Mehr als 10 verfügbar  Mehr als 10 verfügbar
12031                       120                    120
13633                       104                    104
21649                       314                    314
2070                         66                     66
6483                          7                      7
26167                       213                    213
8067                        394                    394
15084                       406                    406
11119     Mehr als 10 verfügbar  Mehr als 10 verfügbar
3728                        119                    119
21363                       115                    115
28641                       355                    355
1469        75 pieces available    75 pieces available

In [62]:
df[df['Items_clean'].str.contains(r'[A-Za-z]', na=False)]['Items_clean'].unique()

array(['2 verfügbar', 'Mehr als 10 verfügbar',
       'jumlah\n\nStok Total: 445', '84 pieces available',
       'jumlah\n\nStok Total: 999999', 'jumlah\n\nStok: 9.992',
       '22 pieces available', '9 pieces available', '44 pieces available',
       '72 pieces available', '74 pieces available',
       'jumlah\n\nStok: 1.498', '24 pieces available',
       '23 pieces available', 'jumlah\n\nStok: 631',
       'jumlah\n\nStok: 639', 'jumlah\n\nStok: Sisa 7',
       'jumlah\n\nStok: 735', 'jumlah\n\nStok: 634',
       'jumlah\n\nStok: 100', 'jumlah\n\nStok: 94', 'jumlah\n\nStok: 129',
       'jumlah\n\nStok Total: 30', 'jumlah\n\nStok Total: 9736',
       'jumlah\n\nStok: 30', 'jumlah\n\nStok: 499',
       'jumlah\n\nStok Total: 285', 'jumlah\n\nStok Total: 68',
       'jumlah\n\nStok: 1.138', 'jumlah\n\nStok: 113 thousand',
       'jumlah\n\nStok: 3.371', 'jumlah\n\nStok Total: 94',
       'jumlah\n\nStok: 2.178', 'jumlah\n\nStok Total: 9560',
       'jumlah\n\nStok Total: 310', 'jumlah\n\nStok: 740',
       'jumlah\n\nStok: 597', 'jumlah\n\nStok: 4.969',
       'jumlah\n\nStok: 4.966', 'jumlah\n\nStok: 2.443',
       'jumlah\n\nStok: 950', 'jumlah\n\nStok: 991',
       'jumlah\n\nStok Total: 912', 'jumlah\n\nStok Total: 96',
       'jumlah\n\nStok: 7.771', 'jumlah\n\nStok: 3.112',
       'jumlah\n\nStok: 5.444', 'jumlah\n\nStok Total: Sisa 5',
       'jumlah\n\nStok: 37', 'jumlah\n\nStok: 4.862',
       'jumlah\n\nStok Total: 722', 'jumlah\n\nStok Total: 169851',
       'jumlah\n\nStok Total: 67', 'jumlah\n\nStok: 3.103',
       'jumlah\n\nStok: 4.176', 'jumlah\n\nStok: 1.005',
       'jumlah\n\nStok: 9.991', 'jumlah\n\nStok: 150',
       'jumlah\n\nStok: 99', '8 pieces available',
       'jumlah\n\nStok: 9.983', 'jumlah\n\nStok: 9.986',
       'jumlah\n\nStok: 9.998', 'jumlah\n\nStok Total: 9921',
       'jumlah\n\nStok Total: 100', 'jumlah\n\nStok Total: 476',
       'jumlah\n\nStok Total: 238', 'jumlah\n\nStok Total: 4976',
       'jumlah\n\nStok Total: 29', '57 pieces available',
       '9994 pieces available', '4 pieces available',
       'jumlah\n\nStok: 1.000', '10 verfügbar', '680 verfügbar',
       '5 verfügbar', '3 verfügbar', '1 pieces available',
       '483 pieces available', '13 pieces available',
       '50 pieces available', '14 pieces available', '679 verfügbar',
       '99 verfügbar', 'jumlah\n\nStok: 135', 'jumlah\n\nStok: 894',
       '49 pieces available', '8999998 pieces available',
       '60 pieces available', '3 pieces available', 'jumlah\n\nStok: 679',
       '75 pieces available', 'jumlah\n\nStok: 1.320', '4 verfügbar',
       'jumlah\n\nStok Total: 866', 'jumlah\n\nStok Total: 65',
       'jumlah\n\nStok: 227', 'jumlah\n\nStok: 335',
       'jumlah\n\nStok: 103', 'jumlah\n\nStok: 115',
       'jumlah\n\nStok: 9.972', '93 pieces available',
       '2 pieces available', 'jumlah\n\nStok Total: 105',
       '63 pieces available', 'jumlah\n\nStok Total: 372',
       'jumlah\n\nStok: 444', 'jumlah\n\nStok: 693',
       '99997 pieces available', 'jumlah\n\nStok: 9.969',
       'jumlah\n\nStok Total: 462', 'jumlah\n\nStok: 138',
       '94 pieces available', 'jumlah\n\nStok Total: 9661',
       '6 pieces available', 'jumlah\n\nStok: 952', 'jumlah\n\nStok: 137',
       'jumlah\n\nStok: 466', '86 pieces available',
       'jumlah\n\nStok: 106thousand', '9992 pieces available',
       'jumlah\n\nStok: 56', 'jumlah\n\nStok: 1.198',
       'jumlah\n\nStok: 104', '678 verfügbar', 'jumlah\n\nStok: 278',
       'jumlah\n\nStok Total: 890', 'jumlah\n\nStok Total: 9912',
       '95 pieces available', '10 pieces available', 'jumlah\n\nStok: 80',
       '16 pieces available'], dtype=object)

In [65]:
# This shows every value with no number at all:
df.loc[
    ~df['Items_clean'].astype(str).str.contains(r'\d', na=False),
    'Items_clean'
].value_counts()

Series([], Name: count, dtype: int64)

In [64]:
#replace text words into 1 first.
df['Items_clean'] = df['Items_clean'].replace({
    'IN STOCK':'1',
    'jumlah\n\nStok: Habis':'1',
    '-':'1'
})

In [46]:
df['Items_clean'].dtype

dtype('O')

In [47]:
df['Items_clean'].isna().sum()

np.int64(0)

In [48]:
(df['Items_clean'] == '1').sum()

np.int64(1449)

In [49]:
df['Items_clean'].value_counts().head(20)

Items_clean
1                        1449
Mehr als 10 verfügbar     899
466                        76
448                        75
371                        75
341                        73
445                        73
496                        73
32                         73
285                        71
108                        70
204                        70
253                        70
226                        69
131                        68
94                         68
49                         68
125                        68
333                        68
491                        67
Name: count, dtype: int64

In [50]:
#check if rows contain rb(means thousand)
df.loc[
    df['Items_clean'].astype(str).str.contains('rb', case=False, na=False),
    'Items_clean'
].unique()

array(['jumlah\n\nStok: 10,6 rb', 'jumlah\n\nStok: 57,8 rb'], dtype=object)

In [51]:
#for clean rows contain rb only and multiply by 1000 
rb_rows = df['Items_clean'].str.contains('rb', case=False, na=False)

df.loc[rb_rows, 'Items_clean'] = (
    df.loc[rb_rows, 'Items_clean']
      .str.extract(r'(\d+[.,]?\d*)')[0]
      .str.replace(',', '.', regex=False)
      .astype(float)
      * 1000
)

In [54]:
df['Items_clean']

0                  2 verfügbar
1                          111
2                          296
3                          984
4        Mehr als 10 verfügbar
                 ...
30490      jumlah\n\nStok: 894
30491                      197
30492                      127
30493    Mehr als 10 verfügbar
30499                       69
Name: Items_clean, Length: 30260, dtype: object

In [58]:
df['Items_clean'] = df['Items_clean'].astype(str)

In [66]:
#To treat other text in between the numbers.
df['Items_clean'] = (df['Items_clean'].str.extract(r'(\d+[.,]?\d*)')[0])

In [67]:
df['Items_clean'].isna().sum()

np.int64(0)

In [68]:
df['Number of items available'] = df['Items_clean']
df.drop(columns=['Items_clean'], inplace=True)

In [69]:
#replace , to . first.
df['Number of items available'] = df['Number of items available'].astype(str).str.replace(',','.',regex=False)

In [70]:
df['Number of items available'] = df['Number of items available'].astype(float)

In [75]:
df['Number of items available'].value_counts().head(20)

Number of items available
1.0      1504
10.0      967
445.0      95
94.0       95
100.0      92
5.0        88
2.0        87
285.0      84
466.0      82
138.0      78
29.0       76
3.0        75
4.0        75
448.0      75
371.0      75
99.0       74
32.0       73
496.0      73
6.0        73
341.0      73
Name: count, dtype: int64

In [80]:
df['Number of items available'].astype(int)

0          2
1        111
2        296
3        984
4         10
        ...
30490    894
30491    197
30492    127
30493     10
30499     69
Name: Number of items available, Length: 30260, dtype: int64

In [81]:
df['Number of items available'].isnull().sum()

np.int64(0)

Number of transactions/number of requests of quotation

In [82]:
df['Transactions_clean'] = df['Number of transactions/number of requests of quotation']

In [83]:
df['Transactions_clean'].value_counts(dropna=False).head(50)

Transactions_clean
0           4398
RFQ only    4349
100+        4344
25          4341
10          4278
5           4256
100         4144
1k            38
1rb           28
33rb          10
21rb           8
11rb           8
4              6
45rb           6
4rb+           4
46rb           3
6              3
23rb+          3
2              2
22             2
44             2
2rb            2
66             2
46             2
31             1
12             1
1 M            1
24             1
112            1
323            1
11             1
56             1
466            1
36rb           1
23 rb          1
23             1
91rb           1
1M             1
33             1
54             1
51rb           1
3rb            1
7              1
8              1
3              1
Name: count, dtype: int64

In [84]:
df['Transactions_clean'].sample(50)

10894         100
28816          10
12433        100+
27026           0
29405        100+
17382           5
23325           5
15610         100
12866         100
18746           0
19542          10
12812         100
6883           25
14301           0
17044           5
17439          25
25920          10
21571         100
15801          25
29061           5
6063     RFQ only
24371    RFQ only
27025          25
15433        100+
27952         100
23963           0
28192         100
13684          10
28388        100+
20405    RFQ only
3501            0
1884          100
19113         1rb
13160          25
29467    RFQ only
29346         100
5127         100+
12432          10
2363     RFQ only
19014        100+
19007        100+
28831    RFQ only
23600    RFQ only
8879            0
4469     RFQ only
18724    RFQ only
8501         100+
12043         100
11039          10
1053          100
Name: Transactions_clean, dtype: object

In [85]:
df['Transactions_clean'].isnull().sum()

np.int64(0)

In [86]:
df['Transactions_clean'].dtype

dtype('O')

To show values containing letters

In [87]:
df[df['Transactions_clean'].str.contains(r'[A-Za-z]', na=False)]['Transactions_clean'].unique()

array(['RFQ only', '1k', '23 rb', '36rb', '1M', '3rb', '51rb', '45rb',
       '46rb', '91rb', '11rb', '21rb', '1rb', '2rb', '33rb', '1 M',
       '4rb+', '23rb+'], dtype=object)

In [88]:
df['Transactions_clean'] = df['Transactions_clean'].astype(str)

In [89]:
#Replace Non numerical text first
df['Transactions_clean']=df['Transactions_clean'].replace('RFQ only','0')

In [90]:
#Convert rb to number*1000
rb = df['Transactions_clean'].str.contains('rb', case=False, na=False)

df.loc[rb, 'Transactions_clean'] = (
    df.loc[rb, 'Transactions_clean']
      .str.extract(r'(\d+[.,]?\d*)')[0]
      .str.replace(',', '.', regex=False)
      .astype(float)
      * 1000
)

In [91]:
#Convert K to number*1000
k = df['Transactions_clean'].str.contains('K', case=False, na=False)

df.loc[k, 'Transactions_clean'] = (
    df.loc[k, 'Transactions_clean']
      .str.extract(r'(\d+[.,]?\d*)')[0]
      .str.replace(',', '.', regex=False)
      .astype(float)
      * 1000
)

In [92]:
#Convert M to number*1000000
M = df['Transactions_clean'].str.contains('M', case=False, na=False)

df.loc[M, 'Transactions_clean'] = (
    df.loc[M, 'Transactions_clean']
      .str.extract(r'(\d+[.,]?\d*)')[0]
      .str.replace(',', '.', regex=False)
      .astype(float)
      * 1000
)

In [93]:
#To check data type of column
df['Transactions_clean'].apply(type).value_counts()

Transactions_clean
<class 'str'>      30143
<class 'float'>      117
Name: count, dtype: int64

In [94]:
df['Transactions_clean'] = df['Transactions_clean'].astype(str)

In [95]:
df['Transactions_clean'] = df['Transactions_clean'].str.replace(',', '', regex=False)

In [96]:
df['Transactions_clean'] = (df['Transactions_clean'].str.extract(r'(\d+[.,]?\d*)')[0])

In [97]:
df['Transactions_clean'] = pd.to_numeric(df['Transactions_clean'])

In [ ]:
df['Transactions_clean'].isnull().sum()

np.int64(0)

In [100]:
df['Number of transactions/number of requests of quotation'] = df['Transactions_clean']
df.drop(columns=['Transactions_clean'], inplace=True)

In [101]:
df['Number of transactions/number of requests of quotation']=df['Number of transactions/number of requests of quotation'].astype(int)

In [102]:
df['Number of transactions/number of requests of quotation'].sample(50)

20289       10
19430        0
29243       10
20835        0
7563         0
8629         0
16991        5
22615      100
14517      100
964          0
8771         0
26641       10
25351        5
23906        5
11257        0
9939       100
5207       100
26602        0
19871      100
360          5
26503       25
228         10
13755        0
556        100
23607        0
11252       25
25061       25
17582      100
8336     21000
10365        0
10498      100
1701         0
6614         0
28163       10
15066      100
14623      100
12463       10
4067       100
13890       25
9620       100
22478        0
17744        5
23648       25
3187         5
678          0
1485       100
15616        0
9673       100
10293        0
7992       100
Name: Number of transactions/number of requests of quotation, dtype: int64

Minimum Order Quantity

In [104]:
df['MIQ']=df['Minimum order quantities']

In [105]:
df['MIQ'].value_counts(dropna=False).head(50)

MIQ
50         5149
1          5067
10         5054
5          5006
MOQ 500    5001
1 Piece    4983
Name: count, dtype: int64

In [106]:
df[df['MIQ'].str.contains(r'[A-Za-z]', na=False)]['MIQ'].unique()

array(['1 Piece', 'MOQ 500'], dtype=object)

In [107]:
df['MIQ']=df['MIQ'].astype(str)

In [108]:
df['MIQ'] = (df['MIQ'].str.extract(r'(\d+[.,]?\d*)')[0])

In [109]:
df['MIQ'].isnull().sum()

np.int64(0)

In [110]:
df['Minimum order quantities'] = df['MIQ']
df.drop(columns=['MIQ'], inplace=True)

In [111]:
df['Minimum order quantities']=df['Minimum order quantities'].astype(int)

In [112]:
df['Minimum order quantities'].dtype

dtype('int64')

Date of analysis

In [113]:
df['Date of analysis'].dtype

dtype('O')

In [114]:
df['Date of analysis'].sample(20)

17539    06/04/2026
8918      12-Jan-26
13295    2025-03-30
9226     28/06/2025
16388    22/01/2025
19309    24/04/2026
25325     16-Feb-25
22219     22-Jan-25
24561     03-Aug-25
16610    2026-04-11
15995    01/12/2025
2784      15-Jun-25
14456    2025-04-17
27061    16/06/2026
27269    2026-06-15
86        12-Jul-25
29131     02-Apr-26
11728    02/02/2025
9        22/03/2025
7567      11-Apr-25
Name: Date of analysis, dtype: object

In [115]:
df['Date of analysis'].sample(20, random_state=42).tolist()

['29-Jun-25',
 '27/04/2026',
 '2025-04-03',
 '19-Jul-25',
 '19/08/2025',
 '10/06/2025',
 '24-Feb-25',
 '11-Oct-25',
 '10-Apr-26',
 '2025-11-20',
 '27/09/2025',
 '06-Jan-26',
 '04/04/2026',
 '24/04/2025',
 '2025-04-20',
 '25-Mar-26',
 '2025-11-19',
 '10/11/2025',
 '28-Mar-26',
 '2025-06-04']

In [116]:
df['Date of analysis'].isna().sum()

np.int64(0)

In [117]:
df['Date of analysis']=pd.to_datetime(df['Date of analysis'],format='mixed',dayfirst=True,errors='coerce')#.dt.strftime('%d-%m-%Y')

In [118]:
df['Date of analysis'].dtype

dtype('<M8[ns]')

Price

In [119]:
df['Price_clean'] = df['Price']

In [120]:
df['Price_clean'].sample(50, random_state=42)

11408                    £15.99
4534                   US $5.63
5715                       ₱420
1610                     Ab 8 €
13225                    197 kr
16328                  US $5.63
8980     Aktueller Preis Ab 6 €
5879                     MX$499
29781                   129 kr.
6206                     197 kr
28380                    197 kr
23916                  US $5.63
16290                  Rp90.000
14880                    197 kr
24161                    MX$499
2276     Aktueller Preis Ab 6 €
7053                        7 €
12709                    MX$499
19347                       7 €
11500                      17 €
29352       Rp82.800 - Rp99.000
15568                   $212.29
16895       Rp82.800 - Rp99.000
26405                    Ab 8 €
10480    Aktueller Preis Ab 6 €
12917       Rp82.800 - Rp99.000
9728                  EUR 11,99
29029             cena 52,00 zł
11858             cena 52,00 zł
22613    Aktueller Preis Ab 6 €
23138                   $212.29
20205                   $212.29
11316                   $212.29
19770                 SGD 18.50
23550                   $212.29
27561                   $212.29
22348             cena 52,00 zł
1616                     MX$499
11082    Aktueller Preis Ab 6 €
6788                  EUR 11,99
2564                       ₱420
14754                    $20.72
13235    Aktueller Preis Ab 6 €
24093                    ₹1,299
9779     Aktueller Preis Ab 6 €
21529                  Rp90.000
12455       Rp82.800 - Rp99.000
11501                    $20.72
17638    Aktueller Preis Ab 6 €
9165        Rp82.800 - Rp99.000
Name: Price_clean, dtype: object

In [121]:
currency_map = {
    'Indonesia': 'IDR',
    'Germany': 'EUR',
    'France': 'EUR',
    'Italy': 'EUR',
    'Spain': 'EUR',
    'Poland': 'PLN',
    'Japan': 'JPY',
    'China': 'CNY',
    'United States': 'USD',
    'Canada': 'CAD',
    'Australia': 'AUD',
    'Singapore': 'SGD',
    'Mexico': 'MXN',
    'Sweden': 'SEK',
    'Denmark': 'DKK',
    'Norway': 'NOK'
}

In [122]:
df['Currency'] = df['Country'].map(currency_map)

In [133]:
df.loc[df['Price'].str.contains('USD|US \$', na=False), 'Currency'] = 'USD'
df.loc[df['Price'].str.contains('EUR|€', na=False), 'Currency'] = 'EUR'
df.loc[df['Price'].str.contains('Rp', na=False), 'Currency'] = 'IDR'
df.loc[df['Price'].str.contains('PLN|zł', na=False), 'Currency'] = 'PLN'
df.loc[df['Price'].str.contains('GBP|£', na=False), 'Currency'] = 'GBP'
df.loc[df['Price'].str.contains('₱', na=False), 'Currency'] = 'PHP'
df.loc[df['Price'].str.contains('RM', na=False), 'Currency'] = 'MYR'
df.loc[df['Price'].str.contains('₹', na=False), 'Currency'] = 'INR'
df.loc[df['Price'].str.contains('SGD', na=False), 'Currency'] = 'SGD'
df.loc[df['Price'].str.contains('MX\$', na=False), 'Currency'] = 'MXN'

In [124]:
df.loc[
    (df['Price'] == '$') &
    (df['Country'] == 'United States'),
    'Currency'
] = 'USD'

df.loc[
    (df['Price'] == '$') &
    (df['Country'] == 'Singapore'),
    'Currency'
] = 'SGD'

df.loc[
    (df['Price'] == '$') &
    (df['Country'] == 'Canada'),
    'Currency'
] = 'CAD'

df.loc[
    (df['Price'] == '$') &
    (df['Country'] == 'Australia'),
    'Currency'
] = 'AUD'

df.loc[
    (df['Price'] == '$') &
    (df['Country'] == 'Mexico'),
    'Currency'
] = 'MXN'

In [125]:
df.loc[
    (df['Price'] == 'kr') &
    (df['Country'] == 'Sweden'),
    'Currency'
] = 'SEK'

df.loc[
    (df['Price'] == 'kr') &
    (df['Country'] == 'Denmark'),
    'Currency'
] = 'DKK'

df.loc[
    (df['Price'] == 'kr') &
    (df['Country'] == 'Norway'),
    'Currency'
] = 'NOK'

In [126]:
df.loc[
    (df['Price'] == '¥') &
    (df['Country'] == 'Japan'),
    'Currency'
] = 'JPY'

df.loc[
    (df['Price'] == '¥') &
    (df['Country'] == 'China'),
    'Currency'
] = 'CNN'

In [127]:
df['Currency'].isna().sum()

np.int64(2305)

In [139]:
df[df['Currency'].isna()][['Country', 'Price']].head(50)

Empty DataFrame
Columns: [Country, Price]
Index: []

In [138]:
df[df['Currency'].isna()]['Price'].value_counts().head(50)

Series([], Name: count, dtype: int64)

In [ ]:
#Treat the symbol as the currency where country doesnt match the symboll.
df.loc[df['Price'].str.contains(r'\$', regex=True, na=False), 'Currency'] = 'USD'

df.loc[df['Price'].str.contains('kr', regex=False, na=False), 'Currency'] = 'SEK'

Price column

In [209]:
df['Price'].value_counts().head(30)

Price
$212.29                               1593
₱420                                  1554
Ab 8 €                                1552
Aktueller Preis Ab 6 €                1541
EUR 12,99/Stk. oder Preisvorschlag    1538
cena 52,00 zł                         1529
Rp90.000                              1529
RM 28.90                              1528
US $5.63                              1521
£15.99                                1515
129 kr.                               1511
MX$499                                1509
Rp82.800 - Rp99.000                   1506
EUR 11,99                             1505
$20.72                                1504
₹1,299                                1489
197 kr                                1466
7 €                                   1461
SGD 18.50                             1460
17 €                                  1449
Name: count, dtype: int64

In [210]:
df['Price_clean'] = df['Price']

In [211]:
df['Price_clean'] = df['Price_clean'].str.extract(r'(\d+[.,]?\d*)')[0]

In [212]:
df['Price_clean'] = df['Price_clean'].str.replace(',', '.', regex=False)

In [213]:
df['Price_clean'].isna().sum()

np.int64(0)

In [215]:
df['Price_clean'] = pd.to_numeric(df['Price_clean'], errors='coerce')

In [216]:
df['Price_clean'].dtype

dtype('float64')

In [217]:
df['Price_clean'].sample(50)

6113       6.000
1423      28.900
9151      28.900
25021     15.990
17796    212.290
27710      8.000
29529     82.800
7978      17.000
18299    212.290
15897     90.000
6683     212.290
3059      52.000
13660     82.800
20118      5.630
28585      6.000
24370    197.000
22062     12.990
5944      15.990
12453      7.000
14582      6.000
13077      7.000
18641     82.800
7597      12.990
15624     82.800
8932       1.299
7358     499.000
21765    420.000
11759     12.990
9828      12.990
4295      17.000
4810      11.990
784       15.990
19651      6.000
29470    499.000
163        7.000
19267     90.000
6134      18.500
13238      1.299
19750     82.800
12893      6.000
18460      8.000
11173    129.000
250       12.990
6664     420.000
19517    212.290
27599     28.900
15447      6.000
29009     11.990
12423     28.900
12832     12.990
Name: Price_clean, dtype: float64

In [ ]:
df['Price_clean'].sample(50)

In [218]:
df['Price'] = df['Price_clean']
df.drop(columns=['Price_clean'], inplace=True)

In [223]:
df['Price'].sum()

np.float64(2800984.711)

Country/Region Mismatch

In [141]:
region_map = {
    'China': 'APAC',
    'India': 'APAC',
    'Indonesia': 'APAC',
    'Malaysia': 'APAC',
    'Singapore': 'APAC',
    'Germany': 'Europe',
    'United States': 'North America'
}

df['Region'] = df['Country'].map(region_map)

In [142]:
pd.crosstab(df['Country'], df['Region'])

Region         APAC  Europe  North America
Country
China          5141       0              0
Germany           0    5053              0
India          5103       0              0
Indonesia       693       0              0
Malaysia       4246       0              0
Singapore      4951       0              0
United States     0       0           5073

In [144]:
df.drop(columns=['Platform Group'], inplace=True)

In [145]:
df.head()

,S.no,Month sequence,Year,Quarter,Month,Third party brand,Platform Type,Platform,Platform domain,Country,...,Minimum order quantities,Type of product,Type of Ip Right Violated,Status,Infringement Type,Remarks,Date of analysis,Currency,Price,Price_clean
0,1,4,2025,2,April,NaN,E-commerce,Alibaba,alibaba.com,Germany,...,5,Razor Cartridge,Labs Cartridge Pattern,Inactive,Counterfeit,NaN,2025-04-25,USD,$212.29,$212.29
1,2,3,2026,1,March,NaN,E-commerce,Shopee,shopee.com.my,China,...,10,Razor Handle,M3 Handle Design,Inactive,Counterfeit,NaN,2026-03-06,EUR,Aktueller Preis Ab 6 €,Aktueller Preis Ab 6 €
2,3,1,2026,1,January,NaN,E-commerce,Deal,deal.by,Germany,...,1,Razor,3D Alpha Mark (Blue),Inactive,counterfeit,NaN,2026-01-03,IDR,Rp82.800 - Rp99.000,Rp82.800 - Rp99.000
3,4,8,2025,3,August,UltraTrim,E-commerce,Amazon,amazon.de,China,...,1,Razor Handle,M3 Handle Design,Inactive,Counterfeit,NaN,2025-08-27,EUR,17 €,17 €
4,5,9,2025,3,September,NaN,E-commerce,1688,1688.com,Malaysia,...,10,Trimmer,Omega Trimmer Shape,Inactive,Counter Fit,NaN,2025-09-08,USD,$212.29,$212.29

In [155]:
df['Third party brand']=df['Third party brand'].fillna('-')

In [158]:
pd.crosstab(df['Month'], df['Quarter'])

Quarter       1     2     3     4
Month
April         0  3458     0     0
August        0     0  1693     0
December      0     0     0  1800
February   3101     0     0     0
January    3485     0     0     0
July          0     0  1810     0
June          0  3028     0     0
March      3479     0     0     0
May           0  3406     0     0
November      0     0     0  1622
October       0     0     0  1733
September     0     0  1645     0

In [159]:
pd.crosstab(df['Month'], df['Month sequence'])

Month sequence,1,2,3,4,5,6,7,8,9,10,11,12
Month,,,,,,,,,,,,
April,0,0,0,3458,0,0,0,0,0,0,0,0
August,0,0,0,0,0,0,0,1693,0,0,0,0
December,0,0,0,0,0,0,0,0,0,0,0,1800
February,0,3101,0,0,0,0,0,0,0,0,0,0
January,3485,0,0,0,0,0,0,0,0,0,0,0
July,0,0,0,0,0,0,1810,0,0,0,0,0
June,0,0,0,0,0,3028,0,0,0,0,0,0
March,0,0,3479,0,0,0,0,0,0,0,0,0
May,0,0,0,0,3406,0,0,0,0,0,0,0
November,0,0,0,0,0,0,0,0,0,0,1622,0
October,0,0,0,0,0,0,0,0,0,1733,0,0
September,0,0,0,0,0,0,0,0,1645,0,0,0

In [176]:
df.isna().sum()

S.no                                                      0
Month sequence                                            0
Year                                                      0
Quarter                                                   0
Month                                                     0
Third party brand                                         0
Platform Type                                             0
Platform                                                  0
Platform domain                                           0
Country                                                   0
Region                                                    0
Seller Name                                               0
URL                                                       0
Item No.                                                  0
Store URL                                                 0
Number of items available                                 0
Number of transactions/number of requests of quotation    0
Minimum order quantities                                  0
Type of product                                           0
Type of Ip Right Violated                                 0
Status                                                    0
Infringement Type                                         0
Date of analysis                                          0
Currency                                                  0
Price                                                     0
Price_clean                                               0
dtype: int64

In [173]:
df['Seller Name'] = df['Seller Name'].fillna('Unknown Seller')

In [175]:
df.drop(columns=['Remarks'], inplace=True)

In [177]:
df.describe()

,S.no,Month sequence,Year,Quarter,Number of items available,Number of transactions/number of requests of quotation,Minimum order quantities,Date of analysis
count,30260.000000,30260.000000,30260.000000,30260.000000,3.026000e+04,30260.000000,30260.000000,30260
mean,15006.453106,5.517019,2025.324289,2.178222,4.436968e+03,78.583939,93.971249,2025-09-27 14:20:54.408460032
min,1.000000,1.000000,2025.000000,1.000000,1.000000e+00,0.000000,1.000000,2025-01-01 00:00:00
25%,7512.750000,3.000000,2025.000000,1.000000,8.600000e+01,0.000000,1.000000,2025-05-14 00:00:00
50%,15005.500000,5.000000,2025.000000,2.000000,2.230000e+02,10.000000,10.000000,2025-09-27 00:00:00
75%,22507.250000,8.000000,2026.000000,3.000000,3.650000e+02,100.000000,50.000000,2026-02-10 00:00:00
max,30000.000000,12.000000,2026.000000,4.000000,8.999998e+06,91000.000000,500.000000,2026-06-25 00:00:00
std,8660.629911,3.325815,0.468117,1.073520,1.871430e+05,1262.481821,181.477214,NaN

In [181]:
df['Country'].value_counts()
#df['Region'].value_counts()
#df['Currency'].value_counts()
#df['Quarter'].value_counts()

Country
China            5141
India            5103
United States    5073
Germany          5053
Singapore        4951
Malaysia         4246
Indonesia         693
Name: count, dtype: int64

Type of Ip Right Violated and Infringement Type inconsistency

In [204]:
pd.crosstab(df['Type of Ip Right Violated'],df['Infringement Type'])

Infringement Type          Design  Trademark
Type of Ip Right Violated
3D Alpha Mark (Blue)            0       3385
Artwork Pattern                 0       3357
Extra Smooth Cartridge       3313          0
Flexball Handle Design       3446          0
Fusion Shade Mark               0       3289
Labs Cartridge Pattern          0       3237
M3 Handle Design             3405          0
Omega Trimmer Shape          3386          0
Vector Shape Mark               0       3442

In [205]:
df['Infringement Type'].unique()

array(['Trademark', 'Design'], dtype=object)

In [193]:
df['Infringement Type'] = df['Infringement Type'].replace({
    'counterfeit': 'Counterfeit',
    'Counter Fit': 'Counterfeit'
})

In [206]:
df['Type of Ip Right Violated'].unique()

array(['Labs Cartridge Pattern', 'M3 Handle Design',
       '3D Alpha Mark (Blue)', 'Omega Trimmer Shape', 'Fusion Shade Mark',
       'Vector Shape Mark', 'Flexball Handle Design', 'Artwork Pattern',
       'Extra Smooth Cartridge'], dtype=object)

In [ ]:
#Trademark-related IPs
trademark = [
    'Labs Cartridge Pattern',
    '3D Alpha Mark (Blue)',
    'Fusion Shade Mark',
    'Vector Shape Mark',
    'Artwork Pattern'
]

df.loc[
    df['Type of Ip Right Violated'].isin(trademark),
    'Infringement Type'
] = 'Trademark'

In [203]:
#Design-related IPs
design = [
    'M3 Handle Design',
    'Flexball Handle Design',
    'Omega Trimmer Shape',
    'Extra Smooth Cartridge'
]

df.loc[
    df['Type of Ip Right Violated'].isin(design),
    'Infringement Type'
] = 'Design'

In [11]:
df['Status'].unique()

<StringArray>
['Removed', 'Active', 'Rejected']
Length: 3, dtype: str

In [10]:
df['Status'] = df['Status'].str.strip()  # remove extra spaces

df['Status'] = df['Status'].replace({
    'Removed': 'Removed',
    'removed': 'Removed',
    'Deactivated': 'Removed',
    'Inactive': 'Removed',

    'Active': 'Active',

    'Active: Rejected': 'Rejected',
    'Not Accepted': 'Rejected'
})

Sort data by Year,Month and update S.No

In [8]:
df = df.sort_values(
    by=['Year', 'Month sequence']
)

In [9]:
df = df.reset_index(drop=True)

In [10]:
df.head()

,S.no,Month sequence,Year,Quarter,Month,Third party brand,Platform Type,Platform,Platform domain,Country,...,Number of items available,Number of transactions/number of requests of quotation,Minimum order quantities,Type of product,Type of Ip Right Violated,Status,Infringement Type,Date of analysis,Currency,Price
0,1,1,2025,1,January,-,E-commerce,CDON,cdon.se,Singapore,...,1.0,1000,50,Razor Cartridge,Labs Cartridge Pattern,Removed,Trademark,2025-01-01,IDR,82.8
1,2,1,2025,1,January,-,E-commerce,Desertcart,desertcart.in,Singapore,...,1.0,25,5,Trimmer,Omega Trimmer Shape,Removed,Design,2025-01-30,SEK,129.0
2,3,1,2025,1,January,-,E-commerce,AliExpress,aliexpress.com,Germany,...,417.0,5,10,Razor Cartridge,Labs Cartridge Pattern,Inactive,Trademark,2025-01-22,EUR,7.0
3,4,1,2025,1,January,-,E-commerce,Allegro,allegro.pl,Singapore,...,149.0,10,50,Razor Handle,M3 Handle Design,Inactive,Design,2025-01-30,PHP,420.0
4,5,1,2025,1,January,-,Social Media,Tiktok,Tiktok.com,India,...,419.0,0,50,Razor Cartridge,Fusion Shade Mark,Inactive,Trademark,2025-01-02,IDR,82.8

In [11]:
df['S.no'] = range(1, len(df) + 1)

In [12]:
df.head()

,S.no,Month sequence,Year,Quarter,Month,Third party brand,Platform Type,Platform,Platform domain,Country,...,Number of items available,Number of transactions/number of requests of quotation,Minimum order quantities,Type of product,Type of Ip Right Violated,Status,Infringement Type,Date of analysis,Currency,Price
0,1,1,2025,1,January,-,E-commerce,CDON,cdon.se,Singapore,...,1.0,1000,50,Razor Cartridge,Labs Cartridge Pattern,Removed,Trademark,2025-01-01,IDR,82.8
1,2,1,2025,1,January,-,E-commerce,Desertcart,desertcart.in,Singapore,...,1.0,25,5,Trimmer,Omega Trimmer Shape,Removed,Design,2025-01-30,SEK,129.0
2,3,1,2025,1,January,-,E-commerce,AliExpress,aliexpress.com,Germany,...,417.0,5,10,Razor Cartridge,Labs Cartridge Pattern,Inactive,Trademark,2025-01-22,EUR,7.0
3,4,1,2025,1,January,-,E-commerce,Allegro,allegro.pl,Singapore,...,149.0,10,50,Razor Handle,M3 Handle Design,Inactive,Design,2025-01-30,PHP,420.0
4,5,1,2025,1,January,-,Social Media,Tiktok,Tiktok.com,India,...,419.0,0,50,Razor Cartridge,Fusion Shade Mark,Inactive,Trademark,2025-01-02,IDR,82.8

In [ ]:
#Save the cleaned dataset
df.to_excel('Brand_Protection_Cleaned.xlsx', index=False)